services:

  voting-postgres:
    image: postgres:16
    container_name: voting-postgres
    environment:
      POSTGRES_DB: voting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  voting-api:
    build: .
    container_name: voting-api
    depends_on:
      - voting-postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local

  k6:
    image: grafana/k6
    container_name: voting-k6
    depends_on:
      - voting-api
    volumes:
      - ./k6:/scripts
    entrypoint: [ "k6", "run", "/scripts/voting-load-test.js" ]

volumes:
  postgres_data: